### DISCUSSION TITLE
How can `local.metadata.yaml` file's embedder_config=>provider be truefoundry for openai's "text-embedding-ada-002" model?

### DISCUSSION THREAD

**Discussion by avibathula** [truefoundry/cognita#161] [Q&A]
THANK YOU FOR creating this repo.

Really interesting project - I was attending a webinar in Oreilly's on LLMs and one of the participants suggested me to look into Cognito - it looks very promising. 

---
## Question 1
Is there any documentation for what all is allowed in `local.metadata.yaml` file?

## Question 2
Looking at the sample provided - how can `embedder_config.provider` be `truefoundry` for model being openai's model `openai-main/text-embedding-ada-002`

What does the usage of "openai-main" mean?

```yaml
collection_name: finance
data_source:
    type: localdir
    uri: ./sample-data/finance
parser_config:
    chunk_size: 1000
    chunk_overlap: 20
    parser_map:
        ".pdf": MultiModalParser
embedder_config:
    provider: truefoundry
    config:
        model: "openai-main/text-embedding-ada-002"
```
