### ISSUE TITLE
dependency failed to start: container infinity is unhealthy

### ISSUE THREAD

**Issue by j-pielen** [truefoundry/cognita#230]
Trying to set it up with docker-compose but it seems that infinity container is not working correctly

Currently under windows 

![image](https://github.com/truefoundry/cognita/assets/165772908/3c3183a7-97e6-4ae3-9f10-46ad1e936f25)

**Comment by S1LV3RJ1NX** [comment]
Can you restart and check? Also your RAM usage, if you have enough space?

**Comment by j-pielen** [comment]
You were right, there was not enough RAM. Anyway i managed to get all containers up and running. Thanks!
However when i want to create a new collection there is no embedding model option in the dropdown ? 
![image](https://github.com/truefoundry/cognita/assets/165772908/9cad214e-11e6-43c9-acf7-3360bb1b4258)

**Comment by S1LV3RJ1NX** [comment]
can you check swagger for infinity service at :7997, and see the list of available models ?

**Comment by chiragjn** [comment]
There are two different issues
1. infinity container shown as unhealthy - This should resolve within few minutes of starting. infinity can take some time to start which - longer than docker compose up might be willing to wait. This is fine
2. There is a problem in `compose.env` and `docker-compose.yaml`. The port is mismatched
https://github.com/truefoundry/cognita/blob/969d75ee530655e75f7bff7882749b2a404a4eca/compose.env#L20
This should be `INFINITY_URL=http://infinity-server:7997`
 
#245 fixes this and bunch of other issues

**Comment by chiragjn** [comment]
Please try from latest main, we have fixed a bunch of issues
Just adding steps as we have changed models_config now to be a yaml spec

```
git pull origin main
cp models_config.sample.yaml models_config.yaml
docker compose --env-file compose.env --profile '*' down
docker compose --env-file compose.env --profile '*' up -d
```

**Comment by chiragjn** [comment]
I am closing this, but please feel free to re-open if things don't work out for you on lastest main :)

**Comment by Amitt1412** [comment]
Hi,


 I have been trying to deploy the app locally using windows, but have been facing the following issue - 

```
 ✔ Service cognita-backend         Built                                                                                                                                     37.5s 
 ✔ Service cognita-frontend        Built                                                                                                                                     25.8s 
 ✔ Network cognita_cognita-docker  Created                                                                                                                                    0.0s 
 ✔ Container qdrant                Healthy                                                                                                                                   25.1s 
 ✔ Container infinity              Started                                                                                                                                   19.1s 
 ✔ Container unstructured-api      Healthy                                                                                                                                   55.1s 
 ✔ Container faster-whisper        Started                                                                                                                                   19.1s 
 ✔ Container ollama                Started                                                                                                                                   19.1s 
 ✘ Container cognita-postgres      Error                                                                                                                                     23.1s 
 ✔ Container cognita-backend       Created                                                                                                                                    0.2s 
 ✔ Container cognita-frontend      Created                                                                                                                                   17.0s 
dependency failed to start: container cognita-postgres is unhealthy
PS C:\Users\AmitTiwari\PycharmProjects\cognita> 
```


I have been using the following config in models_config.yaml. 

```
model_providers:
  ############################ Local ############################################
  #   Uncomment this provider if you want to use local models providers         #
  #   using ollama and infinity model server                                    #
  ###############################################################################

  - provider_name: local-ollama
    api_format: openai
    base_url: http://ollama-server:11434/v1/
    api_key_env_var: ""
    llm_model_ids:
      - "qwen2:1.5b"
    embedding_model_ids: []
    reranking_model_ids: []
    default_headers: {}

  - provider_name: local-infinity
    api_format: openai
    base_url: http://infinity-server:7997/
    api_key_env_var: INFINITY_API_KEY
    llm_model_ids: []
    embedding_model_ids:
      - "mixedbread-ai/mxbai-embed-large-v1"
    reranking_model_ids:
      - "mixedbread-ai/mxbai-rerank-xsmall-v1"
    default_headers: {}

  - provider_name: faster-whisper
    api_format: openai
    base_url: http://faster-whisper:8000
    api_key_env_var: ""
    llm_model_ids: []
    embedding_model_ids: []
    reranking_model_ids: []
    audio_model_ids:
      - "Systran/faster-distil-whisper-large-v3"
    default_headers: {}
############################ OpenAI ###########################################
#   Uncomment this provider if you want to use OpenAI as a models provider    #
#   Remember to set `OPENAI_API_KEY` in container environment                 #
###############################################################################

 - provider_name: openai
   api_format: openai
   api_key_env_var: OPENAI_API_KEY
   llm_model_ids:
     - "gpt-3.5-turbo"
     - "gpt-4o"
   embedding_model_ids:
     - "text-embedding-3-small"
     - "text-embedding-ada-002"
   reranking_model_ids: []
   default_headers: {}

############################ TrueFoundry ###########################################
#   Uncomment this provider if you want to use TrueFoundry as a models provider    #
#   Remember to set `TFY_API_KEY` in container environment                         #
####################################################################################

# - provider_name: truefoundry
#   api_format: openai
#   base_url: https://llm-gateway.truefoundry.com/api/inference/openai
#   api_key_env_var: TFY_API_KEY
#   llm_model_ids:
#     - "openai-main/gpt-4o-mini"
#     - "openai-main/gpt-4-turbo"
#     - "openai-main/gpt-3-5-turbo"
#   embedding_model_ids:
#     - "openai-main/text-embedding-3-small"
#     - "openai-main/text-embedding-ada-002"
#   reranking_model_ids: []
#   default_headers: {}
```

I used your suggested commands this time but have been facing this issue. Please suggest a solution to tackle it down.


Regards
